# Generated by Django 2.0 on 2020-03-01 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Hcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeS', models.CharField(max_length=1)),
                ('codeName', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='holland_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Hcode'),
        ),
    ]
