# Generated by Django 2.1.5 on 2020-03-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='aScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='session',
            name='cScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='session',
            name='eScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='session',
            name='email',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='iScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='session',
            name='rScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='session',
            name='sScore',
            field=models.IntegerField(default=0),
        ),
    ]
